# Generated by Django 2.2 on 2022-04-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_auto_20220413_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cost',
            field=models.BigIntegerField(),
        ),
    ]
