# Generated by Django 2.2 on 2022-04-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comp1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='comp10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='comp2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='comp3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='comp4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='comp5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='comp6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='comp7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='comp8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='comp9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='money',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='account',
            name='prestige',
            field=models.IntegerField(default=0),
        ),
    ]
