# Generated by Django 2.2 on 2022-04-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20220413_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='prestigeBonus',
            field=models.IntegerField(default=0),
        ),
    ]
