# Generated by Django 2.2 on 2022-04-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_account_prestigebonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='prestigeBonus',
            field=models.FloatField(default=0),
        ),
    ]
