# Generated by Django 2.2 on 2022-04-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20220413_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='pcomp1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='pcomp10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='pcomp2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='pcomp3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='pcomp4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='pcomp5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='pcomp6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='pcomp7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='pcomp8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='pcomp9',
            field=models.IntegerField(default=0),
        ),
    ]
